# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
 config.vm.define "ansible-master" do |vm1|
    vm1.vm.hostname = "ansible-master"
    vm1.vm.box = "bento/ubuntu-20.04"
    vm1.vm.network "private_network", ip: "192.178.33.10"
    vm1.vm.provision "setup-hosts", :type => "shell", :path => "ansible-setup.sh"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "ansible-master"
      vb.gui = false
      vb.memory = "1024"
    end
  end

 config.vm.define "ansible-target-1" do |vm2|
   vm2.vm.hostname = "ansible-target-1"
   vm2.vm.box = "bento/ubuntu-20.04"
   vm2.vm.network "private_network", ip: "192.178.33.11"
   vm2.vm.provider "virtualbox" do |vb|
     vb.name = "ansible-target-1"
     vb.gui = false
     vb.memory = "1024"
   end 
 end

 config.vm.define "ansible-target-2" do |vm3|
   vm3.vm.hostname = "ansible-target-2"
   vm3.vm.box = "generic/centos8"
   vm3.vm.network "private_network", ip: "192.178.33.12"
   vm3.vm.provider "virtualbox" do |vb|
     vb.name = "ansible-target-2"
     vb.gui = false
     vb.memory = "1024"
   end
 end
end