# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "terraform" do |vm1|
     vm1.vm.hostname = "terraform"
     vm1.vm.box = "bento/ubuntu-20.04"
     vm1.vm.network "private_network", ip: "192.178.33.16"
     vm1.vm.provision "setup-hosts", :type => "shell", :path => "terraform-setup.sh"
     vm1.vm.provider "virtualbox" do |vb|
       vb.name = "terraform"
       vb.gui = false
       vb.memory = "1024"
     end
   end
 end